env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2021
  sourceType: module
rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]